# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'maingui.ui'
#
# Created by: PyQt5 UI code generator 5.13.0
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(933, 548)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.list_style = QtWidgets.QListWidget(self.centralwidget)
        self.list_style.setGeometry(QtCore.QRect(20, 420, 901, 91))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.list_style.sizePolicy().hasHeightForWidth())
        self.list_style.setSizePolicy(sizePolicy)
        self.list_style.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.list_style.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOn)
        self.list_style.setSizeAdjustPolicy(QtWidgets.QAbstractScrollArea.AdjustToContents)
        self.list_style.setAutoScroll(False)
        self.list_style.setFlow(QtWidgets.QListView.LeftToRight)
        self.list_style.setResizeMode(QtWidgets.QListView.Adjust)
        self.list_style.setViewMode(QtWidgets.QListView.ListMode)
        self.list_style.setObjectName("list_style")
        self.pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton.setGeometry(QtCore.QRect(20, 10, 91, 21))
        self.pushButton.setObjectName("pushButton")
        self.pushButton_2 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_2.setGeometry(QtCore.QRect(840, 20, 81, 21))
        self.pushButton_2.setObjectName("pushButton_2")
        self.groupBox = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox.setGeometry(QtCore.QRect(20, 40, 291, 371))
        self.groupBox.setObjectName("groupBox")
        self.list_src = QtWidgets.QListWidget(self.groupBox)
        self.list_src.setGeometry(QtCore.QRect(10, 290, 271, 71))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.list_src.sizePolicy().hasHeightForWidth())
        self.list_src.setSizePolicy(sizePolicy)
        self.list_src.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.list_src.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOn)
        self.list_src.setSizeAdjustPolicy(QtWidgets.QAbstractScrollArea.AdjustToContents)
        self.list_src.setAutoScroll(False)
        self.list_src.setFlow(QtWidgets.QListView.LeftToRight)
        self.list_src.setResizeMode(QtWidgets.QListView.Adjust)
        self.list_src.setViewMode(QtWidgets.QListView.ListMode)
        self.list_src.setObjectName("list_src")
        self.list_src_show = QtWidgets.QListWidget(self.groupBox)
        self.list_src_show.setGeometry(QtCore.QRect(10, 30, 271, 251))
        self.list_src_show.setResizeMode(QtWidgets.QListView.Adjust)
        self.list_src_show.setObjectName("list_src_show")
        self.groupBox_2 = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox_2.setGeometry(QtCore.QRect(320, 40, 291, 371))
        self.groupBox_2.setObjectName("groupBox_2")
        self.list_dst_show = QtWidgets.QListWidget(self.groupBox_2)
        self.list_dst_show.setGeometry(QtCore.QRect(10, 30, 271, 251))
        self.list_dst_show.setResizeMode(QtWidgets.QListView.Adjust)
        self.list_dst_show.setObjectName("list_dst_show")
        self.groupBox_3 = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox_3.setGeometry(QtCore.QRect(620, 40, 301, 371))
        self.groupBox_3.setObjectName("groupBox_3")
        self.list_lerp_show = QtWidgets.QListWidget(self.groupBox_3)
        self.list_lerp_show.setGeometry(QtCore.QRect(10, 30, 271, 251))
        self.list_lerp_show.setResizeMode(QtWidgets.QListView.Adjust)
        self.list_lerp_show.setObjectName("list_lerp_show")
        self.lerp_slider = QtWidgets.QSlider(self.centralwidget)
        self.lerp_slider.setGeometry(QtCore.QRect(620, 20, 201, 21))
        self.lerp_slider.setMaximum(100)
        self.lerp_slider.setProperty("value", 100)
        self.lerp_slider.setOrientation(QtCore.Qt.Horizontal)
        self.lerp_slider.setObjectName("lerp_slider")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 933, 18))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        self.list_style.setCurrentRow(-1)
        self.list_src.setCurrentRow(-1)
        self.list_style.clicked['QModelIndex'].connect(MainWindow.stylelistClick)
        self.pushButton.clicked.connect(MainWindow.open_src_img)
        self.pushButton_2.clicked.connect(MainWindow.save_dst_img)
        self.lerp_slider.valueChanged['int'].connect(MainWindow.lerp)
        self.list_src.clicked['QModelIndex'].connect(MainWindow.src_list_click)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "剑网3 Ai滤镜 beta v1.0.0"))
        self.pushButton.setText(_translate("MainWindow", "打开原始图片"))
        self.pushButton_2.setText(_translate("MainWindow", "保存生成图片"))
        self.groupBox.setTitle(_translate("MainWindow", "原始图片"))
        self.groupBox_2.setTitle(_translate("MainWindow", "风格图片"))
        self.groupBox_3.setTitle(_translate("MainWindow", "微调"))
